name: flutter_phantom
description: Flutter package for connect phantom wallet And provider methods.
version: 1.0.1
homepage: https://github.com/NavidHosseini/flutter_phantom.git

environment:
  sdk: '>=2.19.0-171.0.dev <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pinenacl: ^0.5.1
  solana_web3: ^0.0.2+4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
